name: Code Check (Lint, Format, Type Check)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install and lint full-kit
        working-directory: full-kit
        run: |
          npm ci
          npm run lint

      - name: Install and lint starter-kit
        working-directory: starter-kit
        run: |
          npm ci
          npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install and check format for full-kit
        working-directory: full-kit
        run: |
          npm ci
          npm run format

      - name: Install and check format for starter-kit
        working-directory: starter-kit
        run: |
          npm ci
          npm run format

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install and type-check full-kit
        working-directory: full-kit
        run: |
          npm ci
          npx tsc --noEmit

      - name: Install and type-check starter-kit
        working-directory: starter-kit
        run: |
          npm ci
          npx tsc --noEmit
